//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mgoo.CarRent.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarRentEntities : DbContext
    {
        public CarRentEntities()
            : base("name=CarRentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apps> Apps { get; set; }
        public virtual DbSet<CarCommandQueue> CarCommandQueue { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<ExceptionMessage> ExceptionMessage { get; set; }
        public virtual DbSet<GeoFence> GeoFence { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LeaseRecord> LeaseRecord { get; set; }
        public virtual DbSet<LeaseUsers> LeaseUsers { get; set; }
        public virtual DbSet<LKLocation> LKLocation { get; set; }
        public virtual DbSet<MobileAppInfo> MobileAppInfo { get; set; }
        public virtual DbSet<WeChatUsers> WeChatUsers { get; set; }
        public virtual DbSet<RechargeRecord> RechargeRecord { get; set; }
        public virtual DbSet<DevicesConfig> DevicesConfig { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual int SP_OfflineMessage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OfflineMessage");
        }
    }
}
