//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mgoo.CarRent.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaseRecord
    {
        public int LeaseID { get; set; }
        public int DeviceID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Fee { get; set; }
        public string UserPhone { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
