//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mgoo.CarRent.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeRecord
    {
        public int RID { get; set; }
        public int UserID { get; set; }
        public string PaymentMethod { get; set; }
        public string TransferMethod { get; set; }
        public System.DateTime TransferTime { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsCheck { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public int Money { get; set; }
        public string ProofImg { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
